Affected Issue(s): #1590675332
What this commit has achieved:
1. Added `name` because the github action
`s4u/maven-settings-action@v2.4.1` was complaining:
```
Prepare maven setings: /home/runner/.m2/settings.xml
maven settings.xml already exists - override
Error: mirrors must contain id, name, mirrorOf and url
```